global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # GreenCode Backend Application
  - job_name: 'greencode-backend'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['greencode-backend:8080']
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node Exporter (if you want to monitor the host system)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # PostgreSQL (if you want to monitor the database)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres:5432']

  # Redis (if you want to monitor the cache)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis:6379']

  # Nginx (if you want to monitor the reverse proxy)
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx:80']
